//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoNgoi__SuatChieu
    {
        public int ChoNgoi_SuatChieu { get; set; }
        public string trangthai { get; set; }
        public Nullable<int> IDSuatChieu { get; set; }
        public Nullable<int> IDChoNgoi { get; set; }
    
        public virtual ChoNgoi ChoNgoi { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
    }
}
