//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DV_VE
    {
        public Nullable<int> IDDichVu { get; set; }
        public Nullable<int> IDVe { get; set; }
        public int IDDV_VE { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual Ve1 Ve1 { get; set; }
    }
}
