//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int IDHoaDon { get; set; }
        public string TenHoaDon { get; set; }
        public double TongTien { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<int> IDVe { get; set; }
    
        public virtual Ve1 Ve1 { get; set; }
    }
}
