//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuatChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuatChieu()
        {
            this.ChoNgoi__SuatChieu = new HashSet<ChoNgoi__SuatChieu>();
            this.Ve1 = new HashSet<Ve1>();
        }
    
        public int IDSuatChieu { get; set; }
        public string TenSuatChieu { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public System.TimeSpan ThoiGianChieu { get; set; }
        public int IDPhongChieu { get; set; }
        public int IDPhim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoNgoi__SuatChieu> ChoNgoi__SuatChieu { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve1> Ve1 { get; set; }
    }
}
